### ISSUE TITLE
Re-licensing?

### ISSUE THREAD

**Issue by JesseTG** [ThelDoctor/CrystalAI#15]
Given that CrystalAI is no longer on the Unity Asset Store, there's no way to obtain a version that's not GPL-licensed. Have you considered re-licensing CrystalAI under something more permissive? I'm considering using CrystalAI in my own project, but I can't use any GPL code in it.

**Comment by romanilyin** [comment]
\+

**Comment by igiagkiozis** [comment]
Hi @JesseTG, @romanilyin, happy to change to the license to MIT; does that work for you?

**Comment by JesseTG** [comment]
Yes, absolutely. Thank you, I appreciate it!

**Comment by romanilyin** [comment]
Yes, thank you.

**Comment by romanilyin** [comment]
Hello. Tell me, please, how soon the license type will be changed to MIT?

**Comment by SurfingNerd** [comment]
Oh yes, MIT would be great. GPL just blocks out most potential games, since open source in game dev is still not big.

**Comment by RedDude** [comment]
@igiagkiozis , did you have changed your mind about the MIT License?

**Comment by igiagkiozis** [comment]
All changed now; enjoy!
